myproject/matcher/urls.py
from django.conf.urls import patterns, url

from matcher import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^(?P<hacker_id>\d+)/$', views.detail, name='detail'),
)

myproject/myproject/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'myproject.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^matcher/', include('matcher.urls', namespace="matcher")),
    url(r'^admin/', include(admin.site.urls)),
)

myproject/matcher/models.py
from django.db import models

# Create your models here.

class Hacker(models.Model):
    DESIGNER = 'DS'
    DEVELOPER = 'DV'
    OTHER = 'OT'
    SKILL_CHOICES = (
        (DESIGNER, 'Designer'),
        (DEVELOPER, 'Developer'),
        (OTHER, 'Other'),
    )
    MALE = 'M'
    FEMALE = 'F'
    OTH = 'O'
    GENDERS = (
        (MALE, 'Male'),
        (FEMALE, 'Female'),
        (OTH, 'Other')
    )
    full_name = models.CharField(max_length=200)
    gender = models.CharField(max_length=2,
                             choices=GENDERS)
    email = models.CharField(max_length=200)
    website = models.CharField(max_length=200)
    details = models.TextField()

    skill = models.CharField(max_length=2,
                             choices=SKILL_CHOICES,
                             default=DESIGNER)
    looking_for = models.CharField(max_length=2,
                             choices=SKILL_CHOICES,
                             default=DEVELOPER)

    def __str__(self):
      return self.full_name

myproject/matcher/views.py
from django.shortcuts import get_object_or_404, render

from django.http import HttpResponse
from django.template import RequestContext, loader

from matcher.models import Hacker

# Create your views here.
def index(request):
   newest_hacker_list = Hacker.objects.all()[:5]
   context = {'newest_hacker_list' : newest_hacker_list}
   return render(request, 'matcher/index.html', context)

def detail(request, hacker_id):
    hacker = get_object_or_404(Hacker, pk=hacker_id)
    return render(request, 'matcher/detail.html', {'hacker': hacker})

myproject/matcher/templates/matcher/detail.html
<div><span class="field">Name:</span> {{ hacker.full_name }}</div>
<div><span class="field">Gender:</span> {{ hacker.get_gender_display }}</div>
<div><span class="field">Primary skill:</span> {{ hacker.get_skill_display }}</div>
<div><span class="field">Looking for:</span> {{ hacker.get_looking_for_display }}</div>
<div><span class="field">Website:</span> <a href="{{ hacker.website }}">{{ hacker.website }}</a></div>
<div><span class="field">Details:</span> {{ hacker.details }}</div>
<div><span class="email"><a href="mailto:{{ hacker.email }}">Email this hacker</a></span></div>

myproject/matcher/templates/matcher/index.html
<h1>Our 5 newest hackers:</h1>
{% if newest_hacker_list %}
	<ul>
	{% for hacker in newest_hacker_list %}
		<li><a href="{% url 'matcher:detail' hacker.id %}">{{ hacker.full_name }}</a></li>
	{% endfor %}
	</ul>
<p>Register now to find awesome people to hack with!</p>
{% else %}
	<p>Nobody has registered for the site lately!</p>
{% endif %}